line-length = 120
target-version = "py313"
lint.pydocstyle.convention = "google"
lint.select = [
    'E',
    'F',
    'W',
    'A',
    'PL',
    'I',
    'TCH',
    'SIM',
    'RUF',
    'ASYNC',
    'C4',
    'INP',
    'ERA',
    'SLF',
    'PIE',
    'PYI',
    'ANN',
    'N',
    'D'
]
lint.ignore = [
    'ANN002',
    'ANN003',
    'D203',
    'D100',
    'D101',
    'D104',
    'RUF012'
]